#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: enredado — Google Drive Picker + Supabase Storage (ticket 03)
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=".env.local"
TOTAL_STAGES=7
DOMAIN="cb53kbbqidm0ekr9ehha2hab.192.99.152.106.sslip.io"

banner "enredado — Google Drive Picker + Supabase Storage"

# ── Stage 1: Proyecto de Google Cloud ──────────────────────────────────────
stage "Crear/elegir el proyecto de Google Cloud"
say "El selector de Drive (Google Picker) necesita un proyecto de Google Cloud"
say "propio, con dos APIs habilitadas: Google Picker API y Google Drive API."
open_url "https://console.cloud.google.com/projectcreate"
step "Creá un proyecto nuevo (nombre sugerido: 'enredado') o elegí uno existente"
step "  que uses solo para esto — no reuses el de otro proyecto sin querer."
pause "¿Ya tenés el proyecto creado/seleccionado?"

# ── Stage 2: Habilitar las APIs ─────────────────────────────────────────────
stage "Habilitar Google Picker API y Google Drive API"
open_url "https://console.cloud.google.com/apis/library/picker.googleapis.com"
step "Click 'Enable' (Habilitar) para Google Picker API."
open_url "https://console.cloud.google.com/apis/library/drive.googleapis.com"
step "Click 'Enable' (Habilitar) para Google Drive API."
pause "¿Ya habilitaste las dos?"

# ── Stage 3: Pantalla de consentimiento OAuth ──────────────────────────────
stage "Configurar la pantalla de consentimiento OAuth"
say "Como esto es solo para tu propio uso (no para terceros), alcanza con"
say "dejar la app en modo 'Testing' y agregarte a vos mismo como test user —"
say "así se evita el proceso de verificación de Google."
open_url "https://console.cloud.google.com/auth/overview"
step "User type: 'External' (o 'Internal' si tu cuenta es de un Workspace propio)."
step "Completá nombre de la app ('enredado'), email de soporte, y guardá."
step "En 'Audience' → 'Test users', agregate a vos mismo (tu email de Google)."
step "Dejala en 'Testing', NO la publiques — así no necesita revisión de Google."
pause "¿Ya configuraste la pantalla de consentimiento y te agregaste como test user?"

# ── Stage 4: OAuth Client ID ────────────────────────────────────────────────
stage "Crear el OAuth Client ID (Web application)"
open_url "https://console.cloud.google.com/auth/clients"
step "Create Client → Application type: 'Web application'. Nombre: 'enredado panel'."
step "En 'Authorized JavaScript origins' agregá (sin barra final):"
note "  https://${DOMAIN}"
step "No hace falta 'Authorized redirect URIs' (el Picker usa un popup, no redirect)."
step "Creá, y copiá el 'Client ID' (termina en .apps.googleusercontent.com)."
ask NEXT_PUBLIC_GOOGLE_CLIENT_ID "Pegá el Client ID:"
write_env NEXT_PUBLIC_GOOGLE_CLIENT_ID "$NEXT_PUBLIC_GOOGLE_CLIENT_ID"

# ── Stage 5: API key para el Picker ────────────────────────────────────────
stage "Crear el API key (Developer Key del Picker)"
open_url "https://console.cloud.google.com/apis/credentials"
step "Create Credentials → API key. Se genera un key nuevo."
step "Click 'Edit API key' → en 'API restrictions' elegí 'Restrict key' y marcá"
step "  solo 'Google Picker API'."
step "En 'Application restrictions' elegí 'Websites' y agregá:"
note "  https://${DOMAIN}/*"
step "Guardá, y copiá el API key."
ask NEXT_PUBLIC_GOOGLE_API_KEY "Pegá el API key:"
write_env NEXT_PUBLIC_GOOGLE_API_KEY "$NEXT_PUBLIC_GOOGLE_API_KEY"

# ── Stage 6: Bucket de Supabase Storage ────────────────────────────────────
stage "Crear el bucket de Supabase Storage (shared-infra)"
say "Se usa como exposición pública temporal: el archivo se sube al momento de"
say "publicar y se borra apenas Meta confirma (o falla) — ver lib/storage/client.ts."
say "Abrí el túnel si no lo tenés: ssh -L 8000:localhost:8000 vps (para Coolify)."
step "Entrá al Supabase Studio de la instancia shared-infra (no el proyecto de"
step "  enredado en Coolify — el Postgres/Storage compartido)."
step "Storage → New bucket → nombre 'enredado-temp' → marcalo 'Public bucket'."
step "Settings del proyecto → API → copiá la 'service_role' key (secret, NO la"
step "  'anon' key que ya tenés)."
warn "El service_role key salta todas las reglas de seguridad (RLS) — nunca lo"
warn "expongas al cliente ni lo commitees. Solo se usa server-side."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Pegá el service_role key:"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

# ── Stage 7: Cargar las variables en Coolify ───────────────────────────────
stage "Cargar las variables en Coolify (producción)"
say "Guardamos las 3 en $ENV_FILE para desarrollo local. Ahora cargalas en Coolify."
open_url "http://localhost:8000"
step "Proyecto 'enredado' → el recurso de la app → pestaña 'Environment Variables'."
step "Cargá (o actualizá) estas 3 claves:"
note "  NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID"
note "  NEXT_PUBLIC_GOOGLE_API_KEY=$NEXT_PUBLIC_GOOGLE_API_KEY"
note "  SUPABASE_SERVICE_ROLE_KEY=<hidden — copialo de $ENV_FILE>"
warn "NEXT_PUBLIC_* se hornean en el build del cliente: sin un Redeploy nuevo,"
warn "el botón de Drive va a seguir roto aunque la variable ya esté cargada."
step "Guardá y dale 'Redeploy' manual (no alcanza con el próximo push a main)."
pause "¿Ya cargaste las 3 variables en Coolify y disparaste el redeploy?"

finish
say "Probá el flujo completo en https://${DOMAIN}/publicar: elegir imagen de"
say "Drive → elegir Cuenta → publicar. Si el Picker no abre, revisá la consola"
say "del navegador — casi siempre es el origin/API key mal restringido."
