#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: enredado — terminar la migración a Instagram API with Instagram
# Login (ver docs/adr/0012-migrar-a-instagram-api-with-instagram-login.md)
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=".env.local"
TOTAL_STAGES=7

APP_URL=$(_existing APP_URL || true)
CALLBACK_URL="${APP_URL:-<tu APP_URL>}/api/meta/callback"

banner "enredado — terminar la migración a Instagram API with Instagram Login"

# ── Stage 1: Instagram App ID + Secret ─────────────────────────────────────
stage "Copiar el Instagram App ID y el Instagram App Secret"
say "El código ya está migrado y deployado (ADR-0012) — el login viejo"
say "(Facebook Login for Business) pedía permisos que Meta dio de baja el"
say "27/1/2025 y nunca iba a poder publicar. Ahora usa 'Instagram API with"
say "Instagram Login', un producto separado con su propio App ID/Secret."
open_url "https://developers.facebook.com/apps/"
step "Entrá a tu App, y en el menú de la izquierda a 'Instagram API' >"
step "  'API setup with Instagram login' (la pantalla de la captura que ya"
step "  me mostraste, con 'enredado-IG' arriba)."
step "Copiá el 'Instagram app ID' (debería ser 954830576968850, confirmalo"
step "  ahí por si cambió)."
ask INSTAGRAM_APP_ID "Pegá el Instagram app ID:"
step "Click 'Show' en 'Instagram app secret', y copialo."
ask_secret INSTAGRAM_APP_SECRET "Pegá el Instagram app secret:"
write_env INSTAGRAM_APP_ID "$INSTAGRAM_APP_ID"
write_env INSTAGRAM_APP_SECRET "$INSTAGRAM_APP_SECRET"

# ── Stage 2: Redirect URI del login de Instagram ───────────────────────────
stage "Registrar el redirect URI en 'Set up Instagram business login'"
say "Es la misma ruta de siempre (/api/meta/callback) — no es nueva, sólo"
say "hay que registrarla también para este producto."
say "Redirect URI a usar: ${CALLBACK_URL}"
step "En la misma pantalla, en '4. Set up Instagram business login', click"
step "  en el botón 'Set up'."
step "Buscá el campo de 'Redirect URIs' / 'OAuth redirect URI' (el nombre"
step "  exacto puede variar) y agregá: ${CALLBACK_URL}"
step "Guardá los cambios ahí."
pause "¿Ya lo guardaste?"

# ── Stage 3: Confirmar Instagram Testers para esta App ─────────────────────
stage "Confirmar que las 4 Cuentas reales son Instagram Tester (aceptado) acá"
say "Puede que ya lo estén de antes (los roles suelen ser a nivel de toda la"
say "App, no por producto) pero hay que confirmarlo, no asumirlo."
open_url "https://developers.facebook.com/apps/"
step "Entrá a 'Roles' > 'Instagram Testers' (o la sección equivalente) de"
step "  esta misma App."
step "Confirmá que las 4 Cuentas de Instagram reales figuran con estado"
step "  'Aceptado' / 'Accepted' (no sólo invitadas)."
if confirm "¿Las 4 figuran como Aceptado?"; then
  note "Bien, seguimos."
else
  warn "Para la(s) que falte(n): agregala en Roles > Instagram Testers desde"
  warn "acá, y esa persona tiene que aceptar la invitación desde la app de"
  warn "Instagram en el celular (Configuración > Apps y sitios web >"
  warn "Invitaciones de tester)."
  pause "Cuando estén todas aceptadas, volvé para seguir."
fi

# ── Stage 4: Cargar las variables en Coolify ───────────────────────────────
stage "Cargar INSTAGRAM_APP_ID/SECRET en Coolify y sacar las viejas"
say "Guardamos las 2 en $ENV_FILE para desarrollo local. Ahora a producción."
open_url "http://localhost:8000"
step "Proyecto 'enredado' → el recurso de la app → 'Environment Variables'."
step "Cargá (o actualizá):"
note "  INSTAGRAM_APP_ID=$INSTAGRAM_APP_ID"
note "  INSTAGRAM_APP_SECRET=<hidden — copialo de $ENV_FILE>"
step "Si siguen cargadas, borrá META_APP_ID, META_APP_SECRET y"
step "  META_LOGIN_CONFIG_ID — el código ya no las usa (ADR-0012)."
warn "Son NEXT_PUBLIC_* no, así que no hace falta un build nuevo del"
warn "cliente — pero como son variables de servidor sí hace falta un"
warn "Redeploy para que el proceso las relea."
step "Guardá y dale 'Redeploy' manual."
pause "¿Ya cargaste las variables y redeployaste?"

# ── Stage 5: Reconectar las 4 Cuentas reales ───────────────────────────────
stage "Reconectar las 4 Cuentas reales desde el panel"
say "Sus tokens actuales (del login viejo) nunca van a poder publicar —"
say "hay que pedir uno nuevo por cada una."
if [[ -n "$APP_URL" ]]; then
  open_url "${APP_URL}/cuentas"
else
  warn "No encontré APP_URL en $ENV_FILE — abrí vos la URL de /cuentas del panel."
fi
step "Para cada una de las 4 Cuentas: desconectala, y conectala de nuevo con"
step "  'Conectar cuenta'."
step "Esta vez el login es directo con Instagram (no aparece un selector de"
step "  Páginas de Facebook como antes) — un login por cada cuenta, con la"
step "  cuenta de Instagram correspondiente."
pause "¿Ya reconectaste las 4?"

# ── Stage 6: Probar publicar ────────────────────────────────────────────────
stage "Probar publicar un Post simple"
if [[ -n "$APP_URL" ]]; then
  open_url "${APP_URL}/publicar"
else
  warn "Abrí vos la URL de /publicar del panel."
fi
step "Elegí una sola foto de Drive, tipo 'Post', cualquiera de las 4 Cuentas"
step "  recién reconectadas, y 'Publicar ahora'."
if confirm "¿Se publicó sin el error (#10) Requires instagram_content_publish?"; then
  note "Migración terminada — publicando de verdad."
else
  warn "Si sigue fallando con el mismo error, revisá primero el Stage 3"
  warn "(Instagram Tester aceptado para ESTA App/producto en particular,"
  warn "no sólo el App ID viejo de Facebook)."
fi

# ── Stage 7: Repetir para las otras 3 Cuentas ───────────────────────────────
stage "Confirmar el resto de las Cuentas"
say "Repetí la prueba del Stage 6 (un Post simple) para las otras 3 Cuentas"
say "reconectadas, una por una, así queda confirmado que las 4 publican."
confirm "¿Las 4 Cuentas publican sin error?" && note "Listo." || warn "Anotá cuál Cuenta específica sigue fallando para seguir desde ahí."
# ──────────────────────────────────────────────────────────────────────────

finish
