#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: enredado — permiso instagram_content_publish rechazado (#10)
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=".env.local"
TOTAL_STAGES=5

META_APP_ID=$(_existing META_APP_ID || true)
APP_URL=$(_existing APP_URL || true)
DASHBOARD_URL="https://developers.facebook.com/apps/${META_APP_ID:-}/dashboard/"

banner "enredado — arreglar \"(#10) Requires instagram_content_publish permission\""

# ── Stage 1: Confirmar qué Cuenta falla ────────────────────────────────────
stage "Confirmar qué Cuenta está fallando"
say "El error \"(#10) Requires instagram_content_publish permission to manage"
say "the object\" es un permiso que Meta le niega al token de esa Cuenta —"
say "no es un bug de código (ver lib/meta/resolve-accounts.ts y"
say "lib/renovacion-token/renovar-token.ts: el token guardado ya es el Page"
say "Access Token correcto, y la renovación automática no le cambia permisos)."
say "La causa más probable: la app de Meta sigue en Development Mode, y para"
say "que instagram_content_publish funcione sobre una Cuenta de Instagram, la"
say "persona dueña de esa cuenta tiene que ACEPTAR la invitación de"
say "\"Instagram Tester\" desde la app de Instagram en el celular — sólo"
say "agregarla como Tester/Admin en el dashboard de Meta no alcanza si esa"
say "invitación quedó sin aceptar."
ask CUENTA_QUE_FALLA "¿Qué Cuenta de Instagram te dio este error? (ej.: @biashop.ar):"
pause "Listo, seguimos con esa Cuenta ($CUENTA_QUE_FALLA)."

# ── Stage 2: Revisar el Instagram Tester invite ────────────────────────────
stage "Revisar si la Cuenta aceptó la invitación de Instagram Tester"
if [[ -n "$META_APP_ID" ]]; then
  open_url "$DASHBOARD_URL"
else
  warn "No encontré META_APP_ID en $ENV_FILE — entrá manual a developers.facebook.com/apps"
  open_url "https://developers.facebook.com/apps/"
fi
step "En el menú de la izquierda, entrá a 'Roles' (o 'App roles')."
step "Buscá la sección 'Instagram Testers' (a veces está dentro de 'Roles',"
step "  a veces en la configuración del producto Instagram — el nombre y la"
step "  ubicación exacta varían según la versión del dashboard)."
step "Fijate el estado de $CUENTA_QUE_FALLA: tiene que decir 'Aceptado' /"
step "  'Accepted', no sólo 'Invitado' / 'Pending'."
if confirm "¿Figura como Aceptado?"; then
  note "Bien — el tester ya estaba aceptado, seguimos."
else
  warn "Ahí está el problema. Falta este paso manual en el celular:"
  step "Abrí la app de Instagram con la cuenta $CUENTA_QUE_FALLA."
  step "Andá a Configuración > Cuenta (o 'Empresa') > 'Apps y sitios web' >"
  step "  'Invitaciones de tester', y aceptá la invitación de esta app."
  step "Si no ves ninguna invitación pendiente ahí, volvé al dashboard de Meta"
  step "  y desde Roles > Instagram Testers reenviala a esa cuenta."
  pause "Aceptá la invitación y volvé acá para seguir."
fi

# ── Stage 3: Confirmar que la Login Configuration sigue con el permiso ─────
stage "Confirmar que la Login Configuration sigue pidiendo instagram_content_publish"
say "Por si se editó sin querer — el ticket 02 dejó la Login Configuration"
say "creada con pages_show_list, pages_read_engagement, instagram_basic e"
say "instagram_content_publish."
if [[ -n "$META_APP_ID" ]]; then
  open_url "$DASHBOARD_URL"
else
  open_url "https://developers.facebook.com/apps/"
fi
step "Buscá 'Facebook Login for Business' > 'Configurations' en el menú."
step "Abrí la Configuration que usa este panel (el config_id está en"
step "  META_LOGIN_CONFIG_ID de tu .env.local, aunque el dashboard no lo"
step "  muestra tal cual — es la única Configuration que debería existir)."
step "Confirmá que 'instagram_content_publish' sigue tildado en la lista de"
step "  permisos."
confirm "¿Sigue tildado?" || warn "Tildalo y guardá antes de seguir — si no, va a rechazar el permiso siempre, para cualquier Cuenta."

# ── Stage 4: Reconectar la Cuenta desde el panel ───────────────────────────
stage "Reconectar la Cuenta en el panel"
say "Aceptar la invitación (o corregir la Configuration) no le cambia el"
say "permiso a un token que Meta ya emitió antes — hay que pedir uno nuevo."
if [[ -n "$APP_URL" ]]; then
  open_url "${APP_URL}/cuentas"
else
  warn "No encontré APP_URL en $ENV_FILE — abrí vos la URL de /cuentas del panel."
fi
step "Desconectá la Cuenta $CUENTA_QUE_FALLA (no borra su historial de"
step "  Publicaciones, sólo el token — ver EstadoCuenta.desconectada)."
step "Conectala de nuevo con 'Conectar', completá el login de Meta, y elegí"
step "  la misma Página de Facebook / Cuenta de Instagram."
pause "¿Ya la reconectaste?"

# ── Stage 5: Probar publicar de nuevo ──────────────────────────────────────
stage "Probar publicar de nuevo"
if [[ -n "$APP_URL" ]]; then
  open_url "${APP_URL}/publicar"
else
  warn "Abrí vos la URL de /publicar del panel."
fi
step "Elegí una sola foto de Drive, tipo 'Post', Cuenta $CUENTA_QUE_FALLA, y"
step "  'Publicar ahora' — el caso más simple, para aislar si ya se arregló."
if confirm "¿Se publicó sin el error (#10)?"; then
  note "Arreglado."
else
  warn "Si sigue el mismo error, puede ser que la app necesite salir de"
  warn "Development Mode (App Review) en vez de Instagram Testers — a partir"
  warn "de acá ya no es algo que se resuelva solo con estos pasos manuales."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
